[build]
  base = "client"
  publish = "dist"
  command = "npm ci && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://player-standings-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
